<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [54]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print(np.ndim(a))
print(np.ndim(b))
print(np.shape(a))
print(np.shape(b))
# ========
print(a)
print(b)

2
2
(100, 100)
(100, 100)
[[0.19839787 0.64643669 0.70850342 ... 0.13151426 0.54887379 0.04456828]
 [0.31922782 0.7200258  0.66821551 ... 0.93635907 0.25656214 0.9499131 ]
 [0.48663459 0.49571596 0.48409613 ... 0.91855202 0.74581291 0.79628002]
 ...
 [0.28607325 0.43304008 0.04677853 ... 0.1013142  0.64637623 0.94909777]
 [0.10670226 0.12326133 0.49633556 ... 0.26476943 0.90517049 0.06463168]
 [0.3612407  0.43642043 0.39644723 ... 0.67657172 0.00618379 0.56998921]]
[[0.16804195 0.97025626 0.27783641 ... 0.36469419 0.7890951  0.01395231]
 [0.32159927 0.73613225 0.85232968 ... 0.05862807 0.63935912 0.29031217]
 [0.2275997  0.66747792 0.05016965 ... 0.61203697 0.61229628 0.53333721]
 ...
 [0.24638472 0.01691659 0.77548844 ... 0.96880581 0.51811429 0.54222347]
 [0.13045315 0.99379299 0.4131657  ... 0.42596999 0.35625419 0.88339374]
 [0.75410995 0.56314999 0.75153205 ... 0.59939518 0.62976155 0.5147026 ]]


In [55]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    res = []
    for i in range(len(a)):
        temp_list = []
        for k in range(len(b[1])):
            temp_sum = 0
            for j in range(len(a)):
                temp_sum += a[i][j] * b[j][k]
            temp_list.append(temp_sum)
        res.append(temp_list)
    return res
        

In [56]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [57]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
print(np.array(M1))

[[26.45181719 27.55898862 29.93697505 ... 28.15284825 27.78742543
  31.25498602]
 [25.42894129 25.63770223 27.68769856 ... 25.71053098 25.22384197
  28.49698381]
 [23.34795627 26.5791141  27.53743896 ... 25.28228768 25.34779024
  26.97255454]
 ...
 [28.73799083 29.55988169 29.53119841 ... 28.30913742 27.31837583
  32.09852215]
 [23.84496389 23.51405589 24.68299536 ... 25.9653944  22.28569505
  26.49564912]
 [24.85872043 26.26092292 26.66755192 ... 26.62535107 22.71480383
  27.47027815]]
Wall time: 574 ms


In [58]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
print(M2)

[[26.45181719 27.55898862 29.93697505 ... 28.15284825 27.78742543
  31.25498602]
 [25.42894129 25.63770223 27.68769856 ... 25.71053098 25.22384197
  28.49698381]
 [23.34795627 26.5791141  27.53743896 ... 25.28228768 25.34779024
  26.97255454]
 ...
 [28.73799083 29.55988169 29.53119841 ... 28.30913742 27.31837583
  32.09852215]
 [23.84496389 23.51405589 24.68299536 ... 25.9653944  22.28569505
  26.49564912]
 [24.85872043 26.26092292 26.66755192 ... 26.62535107 22.71480383
  27.47027815]]
Wall time: 998 µs


In [59]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [73]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.91430031 0.73884337 0.74670815] [0.42908836 0.0786181  0.40543752]


In [74]:
def no_numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    res = 0
    for i in range(len(v1)):
        res += v1[i]*v2[i]
    return res

In [75]:
def numpy_scalar (v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return (v1.T).dot(v2)

In [76]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)
print(no_numpy_scalar(a,b))
print(numpy_scalar(a,b))
# проверим корректность:
assert np.allclose(product_1, product_2)

Wall time: 0 ns
Wall time: 0 ns
0.7531455846176714
0.7531455846176714


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [87]:
def diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    res = 0
    for i in range(a.shape[0]):
        if a[i,i]%2 == 0:
            res += a[i,i]
    return res

In [88]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 1, 9, 5, 3],
       [5, 8, 4, 7, 4],
       [8, 4, 9, 9, 3],
       [8, 4, 8, 5, 3],
       [4, 8, 1, 9, 7]])

In [89]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

Wall time: 0 ns


8

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [90]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    return np.array([np.cumsum(A[i]) for i in range(A.shape[0])])

In [91]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

Wall time: 4.96 ms


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [146]:
from copy import copy
def transform(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    res = np.zeros((X.shape[0],X.shape[1]*2))
    for i in range(X.shape[0]):
        temp = X[i].copy()
        temp[1:X[i].shape[0]:2] = a
        temp[0:X[i].shape[0]:2] **= 3
        print(temp, X[i])
        res[i] = np.concatenate((X[i], temp[::-1]))
    print(res)
    return res

In [147]:
X = np.array([[1,2,3,4,5],[1,2,3,4,5]])
#print(transform(X, 5))
%time S2 = transform(X, 1)

[  1   1  27   1 125] [1 2 3 4 5]
[  1   1  27   1 125] [1 2 3 4 5]
[[  1.   2.   3.   4.   5. 125.   1.  27.   1.   1.]
 [  1.   2.   3.   4.   5. 125.   1.  27.   1.   1.]]
Wall time: 0 ns


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [351]:
def encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    print(a)
    mask = []
    mask2 = [0]
    for i in range(a.shape[0]-1):
        if a[i]!=a[i+1]:
            mask.append(i)
            mask2.append(i+1)
    mask.append(a.shape[0]-1)
    mask2.append(a.shape[0])
    #print(np.array(([i for i in range(a.shape[0]-1)if (a[i]!=a[i+1])]),dtype=int))
    #print(np.array(([i+1 for i in range(a.shape[0]-1)if (a[i]!=a[i+1])]),dtype=int))
    #print(np.array(mask))
    #print(mask2)
    #print(np.nonzero(mask))
    #print(a[np.nonzero(mask)])
    
    return a[mask], np.diff(np.array(mask2))

In [352]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = encode(X)
print(x)
print(num)


[1 2 2 3 3 1 1 5 5 2 3 3]
[0 2 4 6 8 9]
[ 1  3  5  7  9 10]
[ 0  2  4  6  8  9 11]
[0, 1, 3, 5, 7, 9, 10, 12]
(array([1, 2, 3, 4, 5, 6], dtype=int64),)
[2 2 3 3 1 1]
Wall time: 997 µs
[1 2 3 1 5 2 3]
[1 2 2 2 2 1 2]
